# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false

# Properly built package should have no warnings
#warnings_are_errors: false
warnings_are_errors: true

cache: packages
